let num1 = 40;
let num2 = 5;
let sum = num1 + num2;
let difference = num1 - num2;
let product = num1 * num2;
let quotient = num1 / num2;
let remainder = num1 % num2;
console.log("The sum is " + sum + ".");
console.log("The difference is " + difference + ".");
console.log("The product is " + product + ".");
console.log("The quotient is " + quotient + ".");
console.log("The remainder is " + remainder + ".");
